### ISSUE TITLE
Implement initial version of the open API spec

### ISSUE THREAD

**Issue by felix19350** [felix19350/hw-local-manufacturer-search-backend#1]
Use cases: https://docs.google.com/document/d/1U3-uiLBDD7ulAW_rRBNb-jVwewEJWbfBjfhz_ow6NI4/edit

Database model (draft): https://drive.google.com/open?id=1qkVSwTI0ZCSudQQ9kL8QjvNCDLZDq631

The open API spec is a good instrument to enable frontend and backend to talk and iron out and get communication flowing.

**Comment by RRMoelker** [comment]
Not using standard REST interface at the moment.
